### ISSUE TITLE
Using camocomp before background subtraction

### ISSUE THREAD

**Issue by bw4sz** [daien/camocomp#3]
Hi @daien 

I'm developing a [simple background subtraction program](https://github.com/bw4sz/OpenCV_HummingbirdsMotion/tree/master/MotionMeerkat) for biologists to use to extract candidate motion frames from time-lapse videos. These cameras are usually placed in nature, contain long periods of background, followed by brief foreground object ([like a bear cross a trail, or a hummingbird visiting a flower](http://benweinstein.weebly.com/motionmeerkat.html)). The tool works decently well using OpenCV Python bindings and accumulated averaging + some user defined inputs on contour size. I continue to have trouble with intensely variable backgrounds and wind movement. One idea is to pre-stabilize the video and then feed the frames into my scripts. Do you think it would be worth me unpacking your module to get individual frames to process? Or is better to run a full video into your module, and then run the output into my module. I'm trying to decide if there is any time savings by avoiding writing the full temporary (stabilized) video to file. 

Given that i have no stabilization currently, is there any very light settings i can use, i see in your comments that the optimizer is very slow.

Thanks for your work in this area.

**Comment by daien** [comment]
Hi Ben,

I think you should probably avoid stabilizing the full video, especially with my code which is designed for shorter sequences with moving cameras.

As you already have a solution working without stabilization except on these rare problematic cases, I would suggest first trying a simple change detection method to automatically detect these problematic sub-clips. For instance, you can use simple thresholding on the global quantity of motion estimated from temporal differences (or using more costly optical flow if need be). This is all very easy to do with OpenCV. There are other more advanced "change point detection" works in the research literature if you need to dig further.

Once you have such an "event detection" algorithm, you can then try using my code to stabilize only the subclips, or use a stripped down faster version with just keypoint matching and RANSAC. Another promising strategy is to do motion segmentation to separate the moving objects from the (potentially moving) background.

Hope this helps!

Adrien

**Comment by bw4sz** [comment]
Thanks Adrien, I'm on it. Trying to get a decent install of hsi module for python 2.7 and windows (i guess i should just go to 3), failing so far. I'm going to rummage through the code a bit.
